/**
 * catalog.js
 * -----------------------------------------------------------------------------
 * Demo catalogue, written as AI Commerce Profiles.
 *
 * Note the three headphones marked "spec walkthrough" - they reproduce the
 * exact Product A / B / C example from the BuyWise brief, so the scoring demo
 * in the document can be replayed live.
 */

export const DEMO_PRODUCTS = [
  /* ------------------------------------------------------------ headphones */
  {
    name: 'SoundMax Pro ANC',
    brand: 'SoundMax',
    price: 2499,
    mrp: 3499,
    category: 'headphones',
    rating: 4.4,
    ratingCount: 2831,
    description:
      'Over-ear wireless headphones with active noise cancellation and 35 hours of playback, tuned for long study sessions.',
    features: { anc: true, battery: 35, wireless: true, mic: true },
    highlights: ['Active noise cancellation', '35-hour battery life', 'Comfortable memory-foam cups', 'Dual-device pairing'],
    useCases: ['study', 'travel', 'office'],
    suitableFor: ['students', 'travellers', 'office workers'],
    tags: ['anc', 'wireless', 'long battery', 'study'],
  },
  {
    name: 'BassBeat 40H',
    brand: 'BassBeat',
    price: 1999,
    mrp: 2799,
    category: 'headphones',
    rating: 4.1,
    ratingCount: 1907,
    description:
      'Budget wireless headphones with a huge 40-hour battery. No noise cancellation, but excellent value for the price.',
    features: { anc: false, battery: 40, wireless: true, mic: true },
    highlights: ['40-hour battery life', 'Fast charging', 'Lightweight at 210g'],
    useCases: ['travel', 'entertainment', 'office'],
    suitableFor: ['students', 'everyday users'],
    tags: ['budget', 'long battery', 'wireless'],
  },
  {
    name: 'QuietCore Studio',
    brand: 'QuietCore',
    price: 2899,
    mrp: 3999,
    category: 'headphones',
    rating: 4.5,
    ratingCount: 1244,
    description:
      'Studio-style ANC headphones with 32 hours of battery and a low-latency mode, built for focus.',
    features: { anc: true, battery: 32, wireless: true, mic: true },
    highlights: ['Hybrid noise cancellation', '32-hour battery', 'Studio-tuned sound', 'Low-latency mode'],
    useCases: ['study', 'office', 'gaming'],
    suitableFor: ['students', 'office workers'],
    tags: ['anc', 'studio', 'focus'],
  },
  {
    name: 'AirTune Buds 2',
    brand: 'AirTune',
    price: 1299,
    mrp: 1999,
    category: 'headphones',
    rating: 4.0,
    ratingCount: 4102,
    description: 'True wireless earbuds with 24 hours of combined battery and clear call quality.',
    features: { anc: false, battery: 24, wireless: true, mic: true },
    highlights: ['True wireless', '24-hour case battery', 'Sweat resistant'],
    useCases: ['fitness', 'travel', 'entertainment'],
    suitableFor: ['fitness enthusiasts', 'everyday users'],
    tags: ['tws', 'earbuds', 'gym'],
  },
  {
    name: 'FocusOne Silent 45',
    brand: 'FocusOne',
    price: 3799,
    mrp: 4999,
    category: 'headphones',
    rating: 4.6,
    ratingCount: 876,
    description:
      'Premium ANC headphones with 45 hours of playback and an ambient mode for when you need to hear the room.',
    features: { anc: true, battery: 45, wireless: true, mic: true },
    highlights: ['Best-in-class ANC', '45-hour battery', 'Ambient passthrough', 'Multipoint Bluetooth'],
    useCases: ['study', 'office', 'travel'],
    suitableFor: ['students', 'office workers', 'travellers'],
    tags: ['anc', 'premium', 'study', 'long battery'],
  },
  {
    name: 'ClearCall Wired Pro',
    brand: 'ClearCall',
    price: 899,
    mrp: 1299,
    category: 'headphones',
    rating: 3.9,
    ratingCount: 612,
    description: 'Wired over-ear headphones with a boom mic, ideal for online classes and calls.',
    features: { anc: false, battery: 0, wireless: false, mic: true },
    highlights: ['Boom microphone', 'No charging needed', 'In-line volume control'],
    useCases: ['study', 'office'],
    suitableFor: ['students', 'office workers'],
    tags: ['wired', 'calls', 'classes'],
  },

  /* -------------------------------------------------------------- backpacks */
  {
    name: 'TrailGuard Campus 30L',
    brand: 'TrailGuard',
    price: 1499,
    mrp: 2299,
    category: 'backpack',
    rating: 4.5,
    ratingCount: 3210,
    description:
      'Waterproof college backpack with a padded 15.6-inch laptop compartment and a hidden anti-theft pocket.',
    features: { waterproof: true, laptopCompartment: 15.6, antiTheft: true, capacity: 30, weightKg: 0.75 },
    highlights: ['Fully waterproof fabric', 'Padded 15.6" laptop sleeve', 'Hidden anti-theft pocket', '30L capacity'],
    useCases: ['college', 'travel', 'office'],
    suitableFor: ['students', 'travellers', 'office workers'],
    tags: ['waterproof', 'laptop', 'college', 'monsoon'],
  },
  {
    name: 'CityCarry Lite 22L',
    brand: 'CityCarry',
    price: 899,
    mrp: 1399,
    category: 'backpack',
    rating: 4.0,
    ratingCount: 1512,
    description: 'Light everyday backpack with a 14-inch laptop sleeve. Water-resistant, not fully waterproof.',
    features: { waterproof: false, laptopCompartment: 14, antiTheft: false, capacity: 22, weightKg: 0.5 },
    highlights: ['Very light at 500g', '14" laptop sleeve', 'Breathable back panel'],
    useCases: ['college', 'office'],
    suitableFor: ['students'],
    tags: ['light', 'everyday', 'budget'],
  },
  {
    name: 'MonsoonShield 35L',
    brand: 'MonsoonShield',
    price: 1899,
    mrp: 2699,
    category: 'backpack',
    rating: 4.6,
    ratingCount: 2044,
    description:
      'Built for the rainy season: sealed zips, a rain cover and a padded 17-inch laptop compartment.',
    features: { waterproof: true, laptopCompartment: 17, antiTheft: true, capacity: 35, weightKg: 0.95 },
    highlights: ['Sealed zips plus rain cover', 'Fits 17" laptops', 'Lockable anti-theft zips', '35L capacity'],
    useCases: ['college', 'travel'],
    suitableFor: ['students', 'travellers'],
    tags: ['waterproof', 'monsoon', 'rain', 'large'],
  },
  {
    name: 'ExecPro Slim 20L',
    brand: 'ExecPro',
    price: 2499,
    mrp: 3299,
    category: 'backpack',
    rating: 4.3,
    ratingCount: 733,
    description: 'Slim professional backpack with a 15.6-inch compartment and a USB charging port.',
    features: { waterproof: true, laptopCompartment: 15.6, antiTheft: true, capacity: 20, weightKg: 0.8 },
    highlights: ['Professional slim profile', 'USB charging port', 'Water-repellent finish'],
    useCases: ['office', 'travel'],
    suitableFor: ['office workers', 'travellers'],
    tags: ['professional', 'slim', 'office'],
  },
  {
    name: 'Trekster Voyage 45L',
    brand: 'Trekster',
    price: 2799,
    mrp: 3999,
    category: 'backpack',
    rating: 4.4,
    ratingCount: 988,
    description: 'Large travel rucksack with rain cover, compression straps and a laptop sleeve.',
    features: { waterproof: true, laptopCompartment: 15.6, antiTheft: false, capacity: 45, weightKg: 1.3 },
    highlights: ['45L travel capacity', 'Rain cover included', 'Compression straps'],
    useCases: ['travel'],
    suitableFor: ['travellers'],
    tags: ['travel', 'trekking', 'large'],
  },

  /* ---------------------------------------------------------------- laptops */
  {
    name: 'CodeBook Air 14',
    brand: 'CodeBook',
    price: 54990,
    mrp: 62990,
    category: 'laptop',
    rating: 4.5,
    ratingCount: 1420,
    description:
      'Developer laptop with 16GB RAM, a 512GB SSD and a fast 8-core processor in a 1.3kg chassis.',
    features: { ram: 16, storage: 512, processor: 8.5, battery: 12, weightKg: 1.3, display: 8 },
    highlights: ['16GB RAM for heavy multitasking', '512GB SSD', '12-hour battery', 'Just 1.3kg'],
    useCases: ['coding', 'office', 'college'],
    suitableFor: ['developers', 'students', 'office workers'],
    tags: ['coding', 'developer', 'lightweight', 'ssd'],
  },
  {
    name: 'StudyMate 15',
    brand: 'StudyMate',
    price: 38990,
    mrp: 45990,
    category: 'laptop',
    rating: 4.1,
    ratingCount: 2310,
    description: 'Affordable student laptop with 8GB RAM and a 512GB SSD for coursework and browsing.',
    features: { ram: 8, storage: 512, processor: 6.5, battery: 8, weightKg: 1.7, display: 6.5 },
    highlights: ['8GB RAM', '512GB SSD', 'Full-size keyboard'],
    useCases: ['college', 'office'],
    suitableFor: ['students'],
    tags: ['budget', 'student', 'college'],
  },
  {
    name: 'ProForge Creator 16',
    brand: 'ProForge',
    price: 89990,
    mrp: 104990,
    category: 'laptop',
    rating: 4.7,
    ratingCount: 540,
    description: 'Workstation-class laptop with 32GB RAM, a 1TB SSD and a colour-accurate display.',
    features: { ram: 32, storage: 1024, processor: 9.5, battery: 9, weightKg: 2.1, display: 9.5 },
    highlights: ['32GB RAM', '1TB SSD', 'Colour-accurate 16" display', 'Discrete graphics'],
    useCases: ['coding', 'photography', 'gaming'],
    suitableFor: ['developers', 'content creators'],
    tags: ['workstation', 'creator', 'powerful'],
  },
  {
    name: 'RaptorPlay G15',
    brand: 'Raptor',
    price: 72990,
    mrp: 84990,
    category: 'laptop',
    rating: 4.3,
    ratingCount: 1105,
    description: 'Gaming laptop with a 144Hz display, 16GB RAM and dedicated graphics.',
    features: { ram: 16, storage: 1024, processor: 9, battery: 5, weightKg: 2.4, display: 9 },
    highlights: ['144Hz gaming display', 'Dedicated graphics', '16GB RAM', '1TB SSD'],
    useCases: ['gaming', 'coding'],
    suitableFor: ['gamers', 'developers'],
    tags: ['gaming', 'high refresh', 'graphics'],
  },

  /* ----------------------------------------------------------- smartphones */
  {
    name: 'Pixelis 5 Camera Edition',
    brand: 'Pixelis',
    price: 23999,
    mrp: 27999,
    category: 'smartphone',
    rating: 4.5,
    ratingCount: 5620,
    description:
      'Camera-focused phone with a 64MP main sensor, 5000mAh battery and a 120Hz AMOLED display.',
    features: { camera: 64, battery: 22, ram: 8, storage: 128, fiveG: true, display: 9 },
    highlights: ['64MP main camera', '5000mAh all-day battery', '120Hz AMOLED', '5G ready'],
    useCases: ['photography', 'entertainment', 'college'],
    suitableFor: ['content creators', 'students'],
    tags: ['camera', 'amoled', '5g'],
  },
  {
    name: 'Endura Max 6000',
    brand: 'Endura',
    price: 18999,
    mrp: 22999,
    category: 'smartphone',
    rating: 4.3,
    ratingCount: 4890,
    description: 'Battery-first phone with a 6000mAh cell that comfortably lasts two days.',
    features: { camera: 50, battery: 34, ram: 6, storage: 128, fiveG: true, display: 7.5 },
    highlights: ['6000mAh two-day battery', '50MP camera', '5G', '33W fast charging'],
    useCases: ['travel', 'college', 'office'],
    suitableFor: ['students', 'travellers'],
    tags: ['battery', 'long lasting', '5g'],
  },
  {
    name: 'Nova Lite 5G',
    brand: 'Nova',
    price: 13499,
    mrp: 16999,
    category: 'smartphone',
    rating: 4.0,
    ratingCount: 7210,
    description: 'Entry-level 5G phone with a clean interface and a dependable 5000mAh battery.',
    features: { camera: 48, battery: 24, ram: 6, storage: 128, fiveG: true, display: 6.5 },
    highlights: ['5G on a budget', '48MP camera', '5000mAh battery'],
    useCases: ['college', 'entertainment'],
    suitableFor: ['students', 'everyday users'],
    tags: ['budget', '5g', 'entry level'],
  },
  {
    name: 'Zenith Ultra 12',
    brand: 'Zenith',
    price: 47999,
    mrp: 56999,
    category: 'smartphone',
    rating: 4.6,
    ratingCount: 2130,
    description: 'Flagship phone with a 108MP camera system, 12GB RAM and a premium display.',
    features: { camera: 108, battery: 26, ram: 12, storage: 256, fiveG: true, display: 10 },
    highlights: ['108MP triple camera', '12GB RAM', 'Flagship display', '80W charging'],
    useCases: ['photography', 'gaming', 'office'],
    suitableFor: ['content creators', 'gamers'],
    tags: ['flagship', 'camera', 'premium'],
  },

  /* ----------------------------------------------------------- smartwatches */
  {
    name: 'PulseFit Active 2',
    brand: 'PulseFit',
    price: 2999,
    mrp: 4499,
    category: 'smartwatch',
    rating: 4.2,
    ratingCount: 3410,
    description: 'Fitness smartwatch with heart-rate and SpO2 tracking, 10-day battery and IP68 rating.',
    features: { heartRate: true, battery: 240, waterResistant: true, display: 7 },
    highlights: ['Heart rate and SpO2', '10-day battery', 'IP68 water resistant', '100+ sport modes'],
    useCases: ['fitness', 'travel'],
    suitableFor: ['fitness enthusiasts'],
    tags: ['fitness', 'heart rate', 'waterproof'],
  },
  {
    name: 'TimeSync Notify',
    brand: 'TimeSync',
    price: 1799,
    mrp: 2999,
    category: 'smartwatch',
    rating: 4.0,
    ratingCount: 1890,
    description: 'Notification-focused smartwatch with call support and a bright AMOLED screen.',
    features: { heartRate: true, battery: 168, waterResistant: false, display: 8 },
    highlights: ['Bluetooth calling', 'AMOLED display', '7-day battery'],
    useCases: ['office', 'entertainment'],
    suitableFor: ['office workers', 'everyday users'],
    tags: ['notifications', 'calling', 'amoled'],
  },

  /* -------------------------------------------------------------- keyboards */
  {
    name: 'KeyForge TKL Mechanical',
    brand: 'KeyForge',
    price: 3499,
    mrp: 4999,
    category: 'keyboard',
    rating: 4.5,
    ratingCount: 920,
    description: 'Tenkeyless mechanical keyboard with hot-swappable switches and RGB backlighting.',
    features: { mechanical: true, backlit: true, wireless: false },
    highlights: ['Hot-swappable mechanical switches', 'Per-key RGB', 'Compact TKL layout'],
    useCases: ['coding', 'gaming', 'office'],
    suitableFor: ['developers', 'gamers'],
    tags: ['mechanical', 'rgb', 'typing'],
  },
  {
    name: 'SilentType Wireless',
    brand: 'SilentType',
    price: 2199,
    mrp: 2999,
    category: 'keyboard',
    rating: 4.2,
    ratingCount: 1340,
    description: 'Quiet wireless keyboard with backlit keys, built for shared study spaces and offices.',
    features: { mechanical: false, backlit: true, wireless: true, battery: 120 },
    highlights: ['Near-silent keys', 'Wireless with 5-day battery', 'Backlit'],
    useCases: ['office', 'study', 'coding'],
    suitableFor: ['office workers', 'students'],
    tags: ['quiet', 'wireless', 'office'],
  },

  /* --------------------------------------------------------------- monitors */
  {
    name: 'ClearView 24 IPS',
    brand: 'ClearView',
    price: 9499,
    mrp: 12999,
    category: 'monitor',
    rating: 4.3,
    ratingCount: 1620,
    description: '24-inch Full HD IPS monitor with a height-adjustable stand and eye-care mode.',
    features: { display: 8 },
    highlights: ['24" Full HD IPS', 'Height adjustable', 'Flicker-free eye care'],
    useCases: ['office', 'coding', 'college'],
    suitableFor: ['office workers', 'developers', 'students'],
    tags: ['monitor', 'ips', 'work from home'],
  },
  {
    name: 'RapidView 27 165Hz',
    brand: 'RapidView',
    price: 18999,
    mrp: 23999,
    category: 'monitor',
    rating: 4.5,
    ratingCount: 740,
    description: '27-inch QHD gaming monitor running at 165Hz with 1ms response.',
    features: { display: 9.5 },
    highlights: ['27" QHD at 165Hz', '1ms response', 'HDR support'],
    useCases: ['gaming', 'coding'],
    suitableFor: ['gamers', 'developers'],
    tags: ['gaming', 'high refresh', 'qhd'],
  },

  /* --------------------------------------------------------------- speakers */
  {
    name: 'BoomBox Go',
    brand: 'BoomBox',
    price: 2299,
    mrp: 3299,
    category: 'speaker',
    rating: 4.3,
    ratingCount: 2870,
    description: 'Portable Bluetooth speaker with 20 hours of playback and an IPX7 waterproof body.',
    features: { battery: 20, wireless: true, waterResistant: true },
    highlights: ['20-hour playback', 'IPX7 waterproof', 'Stereo pairing'],
    useCases: ['travel', 'fitness', 'entertainment'],
    suitableFor: ['travellers', 'everyday users'],
    tags: ['portable', 'waterproof', 'bluetooth'],
  },
  {
    name: 'HomeStage Soundbar 2.1',
    brand: 'HomeStage',
    price: 5999,
    mrp: 8999,
    category: 'speaker',
    rating: 4.4,
    ratingCount: 1130,
    description: '2.1-channel soundbar with a wireless subwoofer for films and music at home.',
    features: { battery: 0, wireless: true, waterResistant: false },
    highlights: ['2.1 channels with subwoofer', 'HDMI ARC', 'Dedicated movie mode'],
    useCases: ['entertainment'],
    suitableFor: ['everyday users'],
    tags: ['soundbar', 'home theatre', 'movies'],
  },
];
